query getPost($slug: String!) {
  getObjects(
    bucket_slug: "confido"
    read_key: "0O6acZ2ATKQSdKr8rLb5b489Kxg4yNPQRvVii3KCL8T8atx3gn"
    input: {
      query: { type: "posts", slug: $slug }
      props: "title,content,metadata"
    }
  ) {
    objects {
      id
      title
      content
      metadata
    }
  }
}
